#ifndef GENERIC2_H
#define GENERIC2_H
#include "platform.h"

struct GXObject;
struct CollideInfo;

void FUN_00437f40(struct GXObject* gob, int32 param_2);
void FUN_00438470(struct GXObject* gob, int32 param_2);
BOOL event_gxhit(struct GXObject* gob);
BOOL event_hitgx(struct GXObject* gob);
BOOL event_hitPlat(struct GXObject* gob);
BOOL event_hitright(struct GXObject* gob);
BOOL event_hitleft(struct GXObject* gob);
BOOL event_hitground(struct GXObject* gob);
BOOL event_hit45up(struct GXObject* gob);
BOOL event_hit45down(struct GXObject* gob);
BOOL event_ledgeright(struct GXObject* gob);
BOOL event_ledgeleft(struct GXObject* gob);
BOOL event_45right(struct GXObject* gob);
BOOL event_45left(struct GXObject* gob);
BOOL event_pCall(struct GXObject* gob);
BOOL event_hitCeiling(struct GXObject* gob);
BOOL event_topWall(struct GXObject* gob);
BOOL event_gotSpit(struct GXObject* gob);
BOOL event_endPath(struct GXObject* gob);
BOOL event_whacked(struct GXObject* gob);
BOOL event_hitMonster(struct GXObject* gob);
BOOL event_hitContour(struct GXObject* gob);
BOOL event_contourGone(struct GXObject* gob);
BOOL event_flamed(struct GXObject* gob);
BOOL event_buttonpressed(struct GXObject* gob);
BOOL event_voicefinished(struct GXObject* gob);
BOOL event_wallBreak(struct GXObject* gob);
BOOL event_removed(struct GXObject* gob);
void GOB_ProcessXPositionChange(struct GXObject* gob);
void GOB_ProcessYPositionChange(struct GXObject* gob);
int32 ob315_00439110(int32 param_1, int32 param_2);
int32 FUN_00439130(int32 param_1, int32 param_2);
int32 FUN_00439170(int32 param_1);
int32 FUN_00439190(int32 param_1);
int32 FUN_004391b0(int32 param_1);
int32 FUN_004391d0(int32 param_1, int32 param_2, int32 param_3);
void FUN_00439390(int32* param_1, int32* param_2, int32* param_3, int32* param_4);
void FUN_004394b0(struct GXObject* gob);
void FUN_004395b0(int32 x, int32 y);
void FUN_00439640(struct GXObject* gob);
void FUN_004397c0(void);
BOOL FUN_004397f0(void);
void FUN_0043a160(struct GXObject* gob);
void FUN_0043a1f0(void);
void ob315Init(struct GXObject* gob, BOOL removed);
void ob315DoIt(struct GXObject* gob);
void ob315Draw(struct GXObject* gob);
void ob315Clid(struct GXObject* gob, struct CollideInfo* ci);
void ob387Draw(struct GXObject* gob);
void ob371Init(struct GXObject* gob, BOOL removed);
void ob371DoIt(struct GXObject* gob);
void ob371Draw(struct GXObject* gob);
void ob371Clid(struct GXObject* gob, struct CollideInfo* ci);
void SetIntroDistObInit(struct GXObject* gob, BOOL removed);
void ob321Init(struct GXObject* gob, BOOL removed);
void ob321DoIt(struct GXObject* gob);
void ob321Draw(struct GXObject* gob);
void ob321Clid(struct GXObject* gob, struct CollideInfo* ci);
void ob305Init(struct GXObject* gob, BOOL removed);
void ob305DoIt(struct GXObject* gob);
void ob305Draw(struct GXObject* gob);
void ob306Init(struct GXObject* gob, BOOL removed);
void ob306DoIt(struct GXObject* gob);
void ob306Draw(struct GXObject* gob);
void ob307Init(struct GXObject* gob, BOOL removed);
void ob307DoIt(struct GXObject* gob);
void ob307Draw(struct GXObject* gob);
void ob308Init(struct GXObject* gob, BOOL removed);
void ob308DoIt(struct GXObject* gob);
void ob308Draw(struct GXObject* gob);
void ob287Init(struct GXObject* gob, BOOL removed);
void ob287DoIt(struct GXObject* gob);
void ob287Draw(struct GXObject* gob);
void ob271Init(struct GXObject* gob, BOOL removed);
void ob271DoIt(struct GXObject* gob);
void ob271Clid(struct GXObject* gob, struct CollideInfo* ci);
void ob271Draw(struct GXObject* gob);
void ob258Init(struct GXObject* gob, BOOL removed);
void ob258_0043b510(struct GXObject* gob);
void ob258_0043b550(struct GXObject* gob);
void ob258_0043b570(struct GXObject* gob);
void ob258DoIt(struct GXObject* gob);
void ob258Draw(struct GXObject* gob);
void ob258Clid(struct GXObject* gob, struct CollideInfo* ci);
void ob259Init(struct GXObject* gob, BOOL removed);
void ob259DoIt(struct GXObject* gob);
void ob259Draw(struct GXObject* gob);
void ob261Init(struct GXObject* gob, BOOL removed);
void ob261DoIt(struct GXObject* gob);
void ob261Draw(struct GXObject* gob);
void ob261Clid(struct GXObject* gob, struct CollideInfo* ci);
void ob1Init(struct GXObject* gob, BOOL removed);
void ob1DoIt(struct GXObject* gob);
void ob1Draw(struct GXObject* gob);
void ob1Clid(struct GXObject* gob, struct CollideInfo* ci);
void ob89Init(struct GXObject* gob, BOOL removed);
void ob89DoIt(struct GXObject* gob);
void ob89Draw(struct GXObject* gob);
void ob89Clid(struct GXObject* gob, struct CollideInfo* ci);
void ob90Init(struct GXObject* gob, BOOL removed);
void ob90DoIt(struct GXObject* gob);
void ob90Draw(struct GXObject* gob);
void ob90Clid(struct GXObject* gob, struct CollideInfo* ci);
void ob120Init(struct GXObject* gob, BOOL removed);
void ob120DoIt(struct GXObject* gob);
void ob120Draw(struct GXObject* gob);
void ob120Clid(struct GXObject* gob, struct CollideInfo* ci);
void ob121Init(struct GXObject* gob, BOOL removed);
void ob121DoIt(struct GXObject* gob);
void ob121Draw(struct GXObject* gob);
void ob121Clid(struct GXObject* gob, struct CollideInfo* ci);
void ob115Init(struct GXObject* gob, BOOL removed);
void ob218DoIt(struct GXObject* gob);
void ob218Init(struct GXObject* gob, BOOL removed);

#endif
