#ifndef PLAYER2_H
#define PLAYER2_H
#include "platform.h"

struct FrameInfo;
struct GXObject;
struct M1Level;

BOOL FUN_004206b0(int param_1);
uint32 FUN_004206d0(void);
void PlayVoiceIfGexSeesMe(struct GXObject* param_1, int vsitid);
BOOL FUN_004207e0(int32 param_1, int32 param_2);
BOOL FUN_00420820(int32 param_1, int32 param_2);
void GOB_KeepRight(struct GXObject* gob, struct FrameInfo* fi);
void GOB_KeepLeft(struct GXObject* gob, struct FrameInfo* fi);
void GOB_KeepTop(struct GXObject* gob, struct FrameInfo* fi);
void GOB_KeepBottom(struct GXObject* gob, struct FrameInfo* fi);
void GOB_KeepOutOfTiles(struct GXObject* gob);
void GOB_ResetState(struct GXObject* gob);
uint32 GetTileFlagsAtPosition(int32 param_1, int32 param_2);
uint32 FUN_00420c40(struct M1Level* param_1, int32 param_2, int32 param_3);
BOOL FUN_00420c70(struct GXObject* gob);
uint32 FUN_00420ce0(struct GXObject* gob);
void PlayerBubbleDestroy(void);
void PlayerBubbleDraw(int param_1);
void FUN_00420e60(struct GXObject* gob);
void FUN_00420f30(struct GXObject* gob);
uint32 FUN_00420fa0(struct GXObject* gob);
void FUN_00421120(struct GXObject* gob);
void FUN_004211d0(struct GXObject* gob);
BOOL FUN_004212d0(struct GXObject* gob);
void FUN_004213c0(struct M1Level* param_1, struct GXObject* param_2);
void FUN_004213f0(struct GXObject* gob);
void FUN_004214d0(struct GXObject* gob);
void FUN_00421560(struct M1Level* param_1, struct GXObject* param_2);
int FUN_004215d0(struct GXObject* gob);
void EFECT_MakeSplash(struct GXObject* gob);
void FUN_00421740(struct GXObject* gob);
void FUN_00421780(struct GXObject* gob);
BOOL FUN_00421820(struct GXObject* gob);
BOOL FUN_004218a0(struct GXObject* gob);
uint32 PlayerBreakSomething(struct GXObject* gob);
BOOL FUN_004219c0(struct GXObject* gob);
BOOL FUN_00421a00(struct GXObject* gob);
BOOL FUN_00421cc0(void);
void FUN_00421cd0(struct GXObject* gob);
void FUN_00421d50(struct GXObject* param_1, int param_2, int param_3);
void FUN_00421f10(void);
BOOL FUN_00421f20(struct GXObject* gob);
BOOL FUN_00421f90(struct GXObject* gob);
void FUN_00422360(void);
void FUN_00422390(struct GXObject* gob);
void FUN_004223d0(void);
void FUN_00422410(struct GXObject* gob);
void FUN_00422470(struct GXObject* gob);
void FUN_00422500(int param_1);
void FUN_00422580(struct GXObject* param_1, struct GXObject* param_2);
void FUN_00422790(struct GXObject* gob);
void FUN_00423120(void);
void FUN_00423130(struct GXObject* gob);
BOOL FUN_00423190(struct GXObject* gob);
BOOL FUN_004231c0(struct GXObject* gob);
void FUN_00423200(struct GXObject* param_1, struct GXObject* param_2);
void FUN_00423350(struct GXObject* gob);
void FUN_00423760(void);
void FUN_00423780(struct GXObject* gob);
int FUN_004237c0(void);
void FUN_00423800(struct GXObject* gob);
BOOL FUN_00423910(struct GXObject* gob);
BOOL FUN_00423960(struct GXObject* gob);
BOOL FUN_004239b0(struct GXObject* gob);
BOOL FUN_00423a00(struct GXObject* gob);
BOOL FUN_00423a50(struct GXObject* gob);
void FUN_00423aa0(struct GXObject* gob);
BOOL FUN_00423ab0(struct GXObject* gob);
BOOL FUN_00423b00(struct GXObject* gob);
BOOL FUN_00423b40(struct GXObject* gob);
void FUN_00423b80(struct GXObject* gob);
void GX_ResetRotAndScale(struct GXObject* gob);
void PlayerOldMan(struct GXObject* gob);
void InitPlayerOldMan(struct GXObject* gob);
void GetGlueDistAt(struct M1Level* param_1, struct GXObject* gob, int32 x, int32 y);
void PlayerStand(struct GXObject* gob);
void InitPlayerStand(struct GXObject* gob);
void PlayerSlide45(struct GXObject* gob);
void InitPlayerSlide45(struct GXObject* gob);
void PlayerSlide45Jump(struct GXObject* gob);
void InitPlayerSlide45Jump(struct GXObject* gob);
void PlayerPush(struct GXObject* gob);
void InitPlayerPush(struct GXObject* gob);
void FUN_004244e0(struct GXObject* gob, int32 param_2);
BOOL FUN_004245b0(struct GXObject* gob, int32 param_2);
void PlayerWalk(struct GXObject* gob);
void PlayerStartWalkImpl(struct GXObject* gob);
void InitPlayerWalk(struct GXObject* gob);
BOOL FUN_00424980(struct GXObject* gob);
void PlayerRun(struct GXObject* gob);
void InitPlayerRun(struct GXObject* gob);
void PlayerStandJumpStart(struct GXObject* gob);
void InitPlayerStandJumpStart(struct GXObject* gob);
void PlayerStandJump(struct GXObject* gob);
void FUN_00424d80(struct GXObject* gob);
void InitPlayerStandJump(struct GXObject* gob);
void PlayerFall(struct GXObject* gob);
void FUN_00425030(struct GXObject* gob);
void InitPlayerFall(struct GXObject* gob);
void PlayerFalling(struct GXObject* gob);
void FUN_00425250(struct GXObject* gob);
void InitPlayerFalling(struct GXObject* gob);
void PlayerJumpSwallow(struct GXObject* gob);
void InitPlayerJumpSwallow(struct GXObject* gob);
void PlayerJumpTongueLash(struct GXObject* gob);
void InitPlayerJumpTongueLash(struct GXObject* gob);
void PlayerJumpTongueLashUp(struct GXObject* gob);
void InitPlayerJumpTongueLashUp(struct GXObject* gob);
void PlayerJumpTailWhack(struct GXObject* gob);
void InitPlayerJumpTailWhack(struct GXObject* gob);
void PlayerStopFall(struct GXObject* gob);
void InitPlayerStopFall(struct GXObject* gob);
void PlayerStopFalling(struct GXObject* gob);
void InitPlayerStopFalling(struct GXObject* gob);
void PlayerRunJumpStart(struct GXObject* gob);
void InitPlayerRunJumpStart(struct GXObject* gob);
void PlayerRunJump(struct GXObject* gob);
void InitPlayerRunJump(struct GXObject* gob);
void PlayerRunFall(struct GXObject* gob);
void InitPlayerRunFall(struct GXObject* gob);
void PlayerRunStopFall(struct GXObject* gob);
void InitPlayerRunStopFall(struct GXObject* gob);
void PlayerFaceSkew(void);
void InitPlayerFaceSkew(void);
void PlayerFaceTurn(struct GXObject* gob);
void InitPlayerFaceTurn(struct GXObject* gob);
void PlayerFaceStick(struct GXObject* gob);
void InitPlayerFaceStick(struct GXObject* gob);
void PlayerSkid(struct GXObject* param_1);
void InitPlayerSkid(struct GXObject* gob);
void PlayerRunSkidStop(struct GXObject* gob);
void InitPlayerRunSkidStop(struct GXObject* gob);
void PlayerRunSkidding(struct GXObject* gob);
void InitPlayerRunSkidding(struct GXObject* gob);
void PlayerRunSkid(struct GXObject* gob);
void InitPlayerRunSkid(struct GXObject* gob);
void PlayerRunTurnStop(int * param_1);
void InitPlayerRunTurnStop(int * param_1);
void PlayerRunTurn(struct GXObject* gob);
void InitPlayerRunTurn(struct GXObject* gob);
void PlayerTurn(struct GXObject* gob);
void InitPlayerTurn(struct GXObject* gob);
void PlayerSetXAccl(struct GXObject* param_1, int32 param_2);
void PlayerTailSlash(struct GXObject* gob);
void PlayerStartTailSlashImpl(struct GXObject* gob);
void InitPlayerTailSlash(struct GXObject* gob);
void PlayerDuck(struct GXObject* gob);
void InitPlayerDuck(struct GXObject* gob);
void PlayerUnDucking(struct GXObject* gob);
void InitPlayerUnDucking(struct GXObject* gob);
void PlayerDucking(struct GXObject* gob);
void InitPlayerDucking(struct GXObject* gob);
void PlayerTongueLash(struct GXObject* gob);
void InitPlayerTongueLash(struct GXObject* gob);
void PlayerSwallow(struct GXObject* gob);
void InitPlayerSwallow(struct GXObject* gob);
void PlayerSideCrawl(struct GXObject* gob);

#endif