#ifndef PLAYER_H
#define PLAYER_H
#include "platform.h"

struct CollideInfo;
struct FrameInfo;
struct GXObject;

// TODO: Most of these should probably be static in player.c
void FUN_00410d10(uint32 param_1);
void PlayerSetPropertiesForCameraScroll(struct GXObject* gob);
void InitPlayerSideCrawl(struct GXObject* gob);
void FUN_00411230(struct GXObject* gob, struct FrameInfo* param_2, int32* param_3, int32* param_4);
void FUN_004112e0(struct GXObject* gob, uint32 param_2);
void PlayerPlatSideCrawl(struct GXObject* gob);
void InitPlayerPlatSideCrawl(struct GXObject* gob);
void PlayerSideInside45Trans(struct GXObject* gob);
void InitPlayerSideInside45Trans(struct GXObject* gob);
void PlayerSideInside45TransBackward(struct GXObject* gob);
void InitPlayerInside45TransBackward(struct GXObject* gob);
void PlayerSideOutside45Trans(struct GXObject* gob);
void InitPlayerSideOutside45Trans(struct GXObject* gob);
void PlayerSideOutside45TransBackward(struct GXObject* gob);
void InitPlayerSideOutside45TransBackward(struct GXObject* gob);
void PlayerSideInside90Trans(struct GXObject* gob);
void InitPlayerSideInside90Trans(struct GXObject* gob);
void FUN_00411ff0(struct GXObject* gob, int32 param_2, int32 param_3);
void FUN_004120c0(struct GXObject* gob);
void FUN_004121b0(struct GXObject* gob, BOOL param_2, BOOL param_3);
void PlayerSideInside90TransBackward(struct GXObject* gob);
void InitPlayerSideInside90TransBackward(struct GXObject* gob);
void PlayerSideOutside90Trans(struct GXObject* gob);
void InitPlayerSideOutside90Trans(struct GXObject* gob);
void PlayerSideOutside90TransBackward(struct GXObject* gob);
void InitPlayerSideOutside90TransBackward(struct GXObject* gob);
void PlayerSideGetup(struct GXObject* gob);
void InitPlayerSideGetup(struct GXObject* gob);
void PlayerSideUTurn(struct GXObject* gob);
void InitPlayerSideUTurn(struct GXObject* gob);
void PlayerPlatSideGetup(struct GXObject* gob);
void InitPlayerPlatSideGetup(struct GXObject* gob);
void PlayerPlatSideOutside90Trans(struct GXObject* gob);
void InitPlayerOutside90Trans(struct GXObject* gob);
void PlayerPlatSideOutside90TransBackward(struct GXObject* gob);
void InitPlayerPlatSideOutside90TransBackward(struct GXObject* gob);
void PlayerSideTongueLash(struct GXObject* gob);
void InitPlayerSideTongueLash(struct GXObject* gob);
void FUN_00412a00(struct GXObject* gob);
void PlayerFaceSpin(struct GXObject* gob);
void InitPlayerFaceSpin(struct GXObject* gob);
void PlayerFaceWiggle(struct GXObject* gob);
void InitPlayerFaceWiggle(struct GXObject* gob);
void PlayerFaceSpinAround(struct GXObject* gob);
void InitPlayerFaceSpinAround(struct GXObject* gob);
void PlayerFaceUnspin(struct GXObject* gob);
void InitPlayerFaceUnspin(struct GXObject* gob);
void PlayerSideTongueLash90(struct GXObject* gob);
void InitPlayerSideTongueLash90(struct GXObject* gob);
void PlayerSideSpin(struct GXObject* gob);
void InitPlayerSideSpin(struct GXObject* gob);
void PlayerSideSpinAround(struct GXObject* gob);
void InitPlayerSideSpinAround(struct GXObject* gob);
void PlayerSideUnspin(struct GXObject* gob);
void InitPlayerSideUnspin(struct GXObject* gob);
void PlayerSideSlap(struct GXObject* gob);
void InitPlayerSideSlap(struct GXObject* gob);
void PlayerSideTailWhap(struct GXObject* gob);
void InitPlayerTailWhap(struct GXObject* gob);
void PlayerSideJump(struct GXObject* gob);
void InitPlayerSideJump(struct GXObject* gob);
void PlayerFaceTongueLash(struct GXObject* gob);
void InitPlayerFaceTongueLash(struct GXObject* gob);
void PlayerTailBounce(struct GXObject* gob);
void InitPlayerTailBounce(struct GXObject* gob);
void PlayerBounceFall(struct GXObject* gob);
void InitPlayerBounceFall(struct GXObject* gob);
void PlayerBounceUnFall(struct GXObject* gob);
void InitPlayerBounceUnFall(struct GXObject* gob);
void PlayerBounceRise(struct GXObject* gob);
void InitPlayerBounceRise(struct GXObject* gob);
void PlayerAirToSideCrawl(struct GXObject* gob);
void InitPlayerAirToSideCrawl(struct GXObject* gob);
void PlayerPlatAirToSideCrawl(struct GXObject* gob);
void InitPlayerPlatAirToSideCrawl(struct GXObject* gob);
void PlayerAirToFaceCrawl(struct GXObject* gob);
void InitPlayerAirToFaceCrawl(struct GXObject* gob);
void PlayerFaceCrawlToAir(struct GXObject* gob);
void InitPlayerFaceCrawlToAir(struct GXObject* gob);
void PlayerLookup(struct GXObject* gob);
void InitPlayerLookup(struct GXObject* gob);
void PlayerTongueUp(struct GXObject* gob);
void InitPlayerTongueUp(struct GXObject* gob);
void PlayerDuckTongueLash(struct GXObject* gob);
void InitPlayerDuckTongueLash(struct GXObject* gob);
void PlayerDuckSwallow(struct GXObject* gob);
void InitPlayerDuckSwallow(struct GXObject* gob);
void PlayerDuckSpin(struct GXObject* gob);
void InitPlayerDuckSpin(struct GXObject* gob);
void PlayerDuckSpinAround(struct GXObject* gob);
void InitPlayerDuckSpinAround(struct GXObject* gob);
void PlayerDuckUnspin(struct GXObject* gob);
void InitPlayerDuckUnspin(struct GXObject* gob);
void PlayerFaceSwallow(struct GXObject* gob);
void InitPlayerFaceSwallow(struct GXObject* gob);
void PlayerSideSwallow(struct GXObject* gob);
void InitPlayerSideSwallow(struct GXObject* gob);
void FUN_00415170(struct GXObject* gob);
void FUN_004152f0(struct GXObject* gob);
void FUN_004153e0(struct GXObject* gob);
void FUN_00415480(struct GXObject* gob);
void PlayerStartFromCamera(struct GXObject* gob);
void InitPlayerStartFromCamera(struct GXObject* gob);
void PlayerLaunch(struct GXObject* gob);
void InitPlayerLaunch(struct GXObject* gob);
void PlayerLaunchTailBounce(struct GXObject* gob);
void InitPlayerLaunchTailBounce(struct GXObject* gob);
void PlayerShrinkToTube(struct GXObject* gob);
void InitPlayerShrinkToTube(struct GXObject* gob);
void PlayerGoThruTube(struct GXObject* gob);
void InitPlayerGoThruTube(struct GXObject* gob);
void PlayerComeOutTube(struct GXObject* gob);
void InitPlayerComeOutTube(struct GXObject* gob);
void PlayerDoit2(struct GXObject* gob);
void PlayerDoIt(struct GXObject* gob);
void FUN_00416320(struct GXObject* gob);
void PlayerDraw(struct GXObject* gob);
void PlayerInit(struct GXObject* gob, BOOL removed);
void ob302Clid(struct GXObject* gob, struct CollideInfo* ci);
void ob303Clid(struct GXObject* gob, struct CollideInfo* ci);
void PlayerClid(struct GXObject* gob, struct CollideInfo* ci);
void PlayerDamage(void);
void PlayerKill(void);
void FUN_00417d90(void);
void ResetPlayerHP(void);
void InitPlayer(void);

#endif
